
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: bookingz_development

test: &test
  <<: *default
  database: bookingz_test

production:
  <<: *default
  database: bookingz_production
  username: bookingz
  password: <%= ENV['BOOKINGZ_DATABASE_PASSWORD'] %>

cucumber:
  <<: *test